// ─── MOVIE DATA ───
const movies = [
  { id:1, title:'Eeswar', year:2002, poster:'https://upload.wikimedia.org/wikipedia/en/a/ab/Eeswar_film_poster.jpg', genres:['Drama','Action'], category:'vintage', badge:'Debut', badgeClass:'badge-cult', director:'Jayasimha', costars:['Sridevi','Suman'], synopsis:'A young man fights against social injustice after his family is wronged by a powerful landlord — the film that marked Prabhas\'s arrival in Tollywood.', dialogue:'ఆ ఈశ్వరుడికి మూడు కళ్లు ఉంటే... ఈ ఈశ్వరుడికి మూడు గుండెలు ఉన్నాయి!', trailer:'https://www.youtube.com/results?search_query=Eeswar+2002+Prabhas+trailer', release:'20 Sep 2002', budget:3, boxOffice:5, runtime:150, music:'S. A. Rajkumar', language:'Telugu', ott:'Sun NXT, JioCinema' },
  { id:2, title:'Raghavendra', year:2003, poster:'https://upload.wikimedia.org/wikipedia/en/2/20/Raghavendra_poster.jpg', genres:['Drama','Action'], category:'vintage', badge:'Early', badgeClass:'badge-cult', director:'Suresh Krissna', costars:['Ankita','Suman'], synopsis:'A young man named Raghavendra takes on a corrupt system to protect the innocent in this action-packed drama that showcased Prabhas\'s early versatility.', dialogue:'నేను ప్రేమను ఇస్తే ప్రాణం ఇస్తాను... పగను ఇస్తే ప్రాణం తీస్తాను!', trailer:'https://www.youtube.com/results?search_query=Raghavendra+2003+Prabhas+trailer', release:'10 Oct 2003', budget:4, boxOffice:6, runtime:155, music:'Koti', language:'Telugu', ott:'Amazon Prime Video, aha, ETV Win' },
  { id:3, title:'Varsham', year:2004, poster:'https://upload.wikimedia.org/wikipedia/en/9/90/Varsham_2004_poster.jpg', genres:['Action','Romance'], category:'vintage', badge:'Cult Classic', badgeClass:'badge-cult', director:'Sobhan', costars:['Trisha','Gopichand'], synopsis:'A daring young man falls in love while protecting his family from a vengeful criminal in this action-romance that became Prabhas\'s first major success.', dialogue:'నేను శైలు కోసం వంద సార్లు చస్తా... నువ్వు ఒక్క సారి చస్తావా?', trailer:'https://www.youtube.com/results?search_query=Varsham+2004+Prabhas+trailer', release:'14 Jan 2004', budget:5, boxOffice:15, runtime:152, music:'Devi Sri Prasad', language:'Telugu', ott:'Amazon Prime Video' },
  { id:4, title:'Adavi Ramudu', year:2004, poster:'https://upload.wikimedia.org/wikipedia/en/8/8f/Adavi_Ramudu.jpg', genres:['Action','Drama'], category:'vintage', badge:'Action', badgeClass:'badge-cult', director:'B. Gopal', costars:['Aarti Agarwal','Suman'], synopsis:'A forest dweller fights against a ruthless landlord who exploits the tribal people, showcasing Prabhas in a rugged, raw avatar.', dialogue:'అడవిలో బ్రతికేటోళ్లం సార్... న్యాయం కోసం ప్రాణాలు ఇస్తాం, అన్యాయం చేస్తే ప్రాణాలు తీస్తాం!', trailer:'https://www.youtube.com/results?search_query=Adavi+Ramudu+2004+Prabhas+trailer', release:'09 Jul 2004', budget:6, boxOffice:8, runtime:148, music:'Mani Sharma', language:'Telugu', ott:'Sun NXT' },
  { id:5, title:'Chakram', year:2005, poster:'https://upload.wikimedia.org/wikipedia/en/3/31/Chakram_poster.jpg', genres:['Action','Drama'], category:'vintage', badge:'Drama', badgeClass:'badge-cult', director:'Krishna Vamsi', costars:['Asin','Charmy'], synopsis:'A man with a mysterious past embarks on a journey of redemption while protecting a young girl in this emotionally charged drama.', dialogue:'జీవితం ఒక చక్రం — తిరిగి తిరిగి వస్తుంది.', trailer:'https://www.youtube.com/results?search_query=Chakram+2005+Prabhas+trailer', release:'24 Jun 2005', budget:7, boxOffice:10, runtime:166, music:'Chakri', language:'Telugu', ott:'aha, ZEE5, MX Player' },
  { id:6, title:'Chatrapathi', year:2005, poster:'https://upload.wikimedia.org/wikipedia/en/e/eb/Chhatrapati_movie_poster.jpg', genres:['Action','Drama'], category:'blockbuster', badge:'Blockbuster', badgeClass:'badge-blockbuster', director:'S. S. Rajamouli', costars:['Shriya','Bhanu Chander'], synopsis:'An orphaned boy grows up to become a powerful leader who fights for the oppressed in this epic action-drama that marked Prabhas\'s first collaboration with S. S. Rajamouli.', dialogue:'వాడు పోతే వీడు... వీడు పోతే నేను... నేను పోతే నా అమ్మ మొగుడు అంటూ ఎవరైనా అధికారం కోసం ఎగబడితే...!!', trailer:'https://www.youtube.com/results?search_query=Chatrapathi+2005+Prabhas+trailer', release:'29 Sep 2005', budget:12, boxOffice:30, runtime:150, music:'M. M. Keeravani', language:'Telugu', ott:'Amazon Prime Video' },
  { id:7, title:'Pournami', year:2006, poster:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtx8t7EOb9lNj_PalaM6g_w37k9XF-w6X95HSrm00Sew&s=10', genres:['Action','Romance'], category:'vintage', badge:'Romance', badgeClass:'badge-cult', director:'Prabhu Deva', costars:['Trisha','Rahul Dev'], synopsis:'A royal bodyguard falls in love with a princess while protecting her from political intrigue in this period romance-action film.', dialogue:'హృదయానికి సరిహద్దులు లేవు.', trailer:'https://www.youtube.com/results?search_query=Pournami+2006+Prabhas+trailer', release:'20 Apr 2006', budget:10, boxOffice:14, runtime:157, music:'Devi Sri Prasad', language:'Telugu', ott:'Amazon Prime Video' },
  { id:8, title:'Yogi', year:2007, poster:'https://upload.wikimedia.org/wikipedia/en/d/d3/Yogi.dvd.jpg', genres:['Action','Drama'], category:'vintage', badge:'Action', badgeClass:'badge-cult', director:'V. V. Vinayak', costars:['Nayanthara','Suman'], synopsis:'A hot-headed young man known as Yogi takes on a dangerous gang to save his village and win back his love.', dialogue:'నా నెత్తురుకి ఉడుకెక్కువ... నా కత్తికి పదునెక్కువ!', trailer:'https://www.youtube.com/results?search_query=Yogi+2007+Prabhas+trailer', release:'12 Jan 2007', budget:8, boxOffice:16, runtime:156, music:'Ramana Gogula', language:'Telugu', ott:'ZEE5' },
  { id:9, title:'Munna', year:2007, poster:'https://upload.wikimedia.org/wikipedia/en/6/6b/Munna_film_poster.jpg', genres:['Action','Comedy'], category:'vintage', badge:'Comedy', badgeClass:'badge-cult', director:'Vamsi Paidipally', costars:['Ileana','Prakash Raj'], synopsis:'A fun-loving guy named Munna gets caught in a web of crime and family secrets while trying to win the girl of his dreams.', dialogue:'ఎవరైనా నీ మీద ప్రేమ చూపిస్తే అది ఈవ్ టీజింగ్ కాదు... అది కంప్లిమెంట్. నచ్చితే ఎస్ చెప్పు, నచ్చకపోతే నో చెప్పు.', trailer:'https://www.youtube.com/results?search_query=Munna+2007+Prabhas+trailer', release:'31 Aug 2007', budget:10, boxOffice:18, runtime:165, music:'Harris Jayaraj', language:'Telugu', ott:'ZEE5, Hungama Play' },
  { id:10, title:'Bujjigadu', year:2008, poster:'https://upload.wikimedia.org/wikipedia/en/0/00/Bujjigaadu_poster.jpg', genres:['Action','Comedy'], category:'vintage', badge:'Action', badgeClass:'badge-cult', director:'Puri Jagannadh', costars:['Trisha','Sonu Sood'], synopsis:'A orphaned boy grows up in Chennai and returns to his village to fulfill a promise, taking on the local don in this mass entertainer.', dialogue:'టిప్పర్ లారీ వెళ్లి స్కూటర్ ని కుడితే ఎలా ఉంటాడో తెలుసా? అలా ఉంటుంది నేను గుడిథె.', trailer:'https://www.youtube.com/results?search_query=Bujjigadu+2008+Prabhas+trailer', release:'09 May 2008', budget:12, boxOffice:20, runtime:158, music:'Koti', language:'Telugu', ott:'Amazon Prime Video' },
  { id:11, title:'Billa', year:2009, poster:'https://upload.wikimedia.org/wikipedia/en/6/63/Billa_Telugu_Film_Poster.jpg', genres:['Action','Thriller'], category:'action', badge:'Cult Classic', badgeClass:'badge-cult', director:'Meher Ramesh', costars:['Anushka','Krishnam Raju'], synopsis:'A look-alike of a dreaded don is recruited by the police to infiltrate the underworld in this stylish action-thriller remake.', dialogue:'బిల్లా ఎవరికీ టార్గెట్ అవ్వడు... ట్రస్ట్ నో వన్, కిల్ ఎవ్రీవన్, బి ఓన్లీ వన్... బిల్లా!', trailer:'https://www.youtube.com/results?search_query=Billa+2009+Prabhas+trailer', release:'05 Feb 2009', budget:15, boxOffice:25, runtime:170, music:'Mani Sharma', language:'Telugu', ott:'Sun NXT' },
  { id:12, title:'Ek Niranjan', year:2009, poster:'https://upload.wikimedia.org/wikipedia/en/3/31/Ek_Niranjan_poster.jpg', genres:['Action','Romance'], category:'vintage', badge:'Drama', badgeClass:'badge-cult', director:'Puri Jagannadh', costars:['Kangana Ranaut','Sonu Sood'], synopsis:'A young man named Chotu, who works as a hitman, discovers love and redemption while trying to protect a little girl from his past.', dialogue:'మీలో ఎవడికైనా నన్నిలా కొట్టే ధమ్ముందా?', trailer:'https://www.youtube.com/results?search_query=Ek+Niranjan+2009+Prabhas+trailer', release:'14 Aug 2009', budget:14, boxOffice:22, runtime:170, music:'Mani Sharma', language:'Telugu', ott:'ZEE5, MX Player, Amazon Prime Video' },
  { id:13, title:'Darling', year:2010, poster:'https://upload.wikimedia.org/wikipedia/en/b/b7/Darling_%282010%29_poster.jpg', genres:['Romance','Comedy'], category:'vintage', badge:'Cult Classic', badgeClass:'badge-cult', director:'A. Karunakaran', costars:['Kajal Aggarwal','Prabhu'], synopsis:'A charming young man wins back his childhood love after a series of comedic misunderstandings in this heartwarming romantic comedy that became a fan favorite.', dialogue:'బలం అనేది ప్రదర్శనకు కాదు... అవసరం వచ్చినప్పుడు బయటకు వస్తుంది.', trailer:'https://www.youtube.com/results?search_query=Darling+2010+Prabhas+trailer', release:'23 Jul 2010', budget:12, boxOffice:25, runtime:156, music:'G. V. Prakash Kumar', language:'Telugu', ott:'Amazon Prime Video' },
  { id:14, title:'Mr. Perfect', year:2011, poster:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8piqnKYyRpc5wR_TRDpPvuX8XxmCQy_FkJW3LZ0avyA&s=10', genres:['Romance','Comedy'], category:'vintage', badge:'Hit', badgeClass:'badge-hit', director:'Dasaradh', costars:['Kajal Aggarwal','Taapsee Pannu'], synopsis:'A perfectionist businessman learns that life and love are not about being perfect, but about being present, in this feel-good romantic comedy.', dialogue:'గెలవాలంటే లోంగాలి వొంగాలి అంటే నేను నమ్మను... మనలో మ్యాటర్ ఉండాలి.', trailer:'https://www.youtube.com/results?search_query=Mr+Perfect+2011+Prabhas+trailer', release:'22 Apr 2011', budget:15, boxOffice:35, runtime:148, music:'Devi Sri Prasad', language:'Telugu', ott:'Amazon Prime Video' },
  { id:15, title:'Rebel', year:2012, poster:'https://upload.wikimedia.org/wikipedia/en/5/50/Rebel_Movie_Poster_Prabhas.jpg', genres:['Action','Drama'], category:'action', badge:'Action', badgeClass:'badge-cult', director:'Raghava Lawrence', costars:['Tamannaah','Devi Sri Prasad'], synopsis:'A young man returns from abroad to find his family in turmoil and transforms into a rebel to fight against a corrupt politician.', dialogue:'వాళ్లకి చెప్పు... నేను యముడి రూపంలో వచ్చిన రెబెల్.', trailer:'https://www.youtube.com/results?search_query=Rebel+2012+Prabhas+trailer', release:'28 Sep 2012', budget:35, boxOffice:45, runtime:163, music:'Raghava Lawrence', language:'Telugu', ott:'Amazon Prime Video, Sun NXT' },
  { id:16, title:'Mirchi', year:2013, poster:'https://upload.wikimedia.org/wikipedia/en/a/a8/Mirchi_film_poster.jpg', genres:['Action','Romance'], category:'action', badge:'Hit', badgeClass:'badge-hit', director:'Koratala Siva', costars:['Anushka','Richa Panai'], synopsis:'A man returns to his hometown to resolve a long-standing family feud, using peace and wit instead of violence to win hearts.', dialogue:'కటౌట్ చూసి కొన్ని కొన్ని నమ్మేయాలి డ్యూడ్...', trailer:'https://www.youtube.com/results?search_query=Mirchi+2013+Prabhas+trailer', release:'14 Feb 2013', budget:20, boxOffice:50, runtime:155, music:'Devi Sri Prasad', language:'Telugu', ott:'Amazon Prime Video' },
  { id:18, title:'Baahubali: The Beginning', year:2015, poster:'https://upload.wikimedia.org/wikipedia/en/5/5f/Baahubali_The_Beginning_poster.jpg', genres:['Action','Epic','Fantasy'], category:'blockbuster', badge:'Blockbuster', badgeClass:'badge-blockbuster', director:'S. S. Rajamouli', costars:['Rana Daggubati','Anushka','Tamannaah'], synopsis:'A young man discovers his royal lineage and takes on an empire to avenge his mother\'s death in this magnum opus that rewrote Indian cinema and placed Prabhas on the global stage.', dialogue:'మాహిష్మతి ఊపిరి పీల్చుకో... నా కొడుకు వచ్చాడు... బాహుబలి తిరిగి వచ్చాడు!', trailer:'https://www.youtube.com/watch?v=VdafjyFK3ko', release:'10 Jul 2015', budget:180, boxOffice:650, runtime:159, music:'M. M. Keeravani', language:'Telugu, Tamil', ott:'Netflix' },
  { id:19, title:'Baahubali 2: The Conclusion', year:2017, poster:'https://upload.wikimedia.org/wikipedia/en/9/93/Baahubali_2_The_Conclusion_poster.jpg', genres:['Action','Epic','Fantasy'], category:'blockbuster', badge:'Industry Hit', badgeClass:'badge-industry', director:'S. S. Rajamouli', costars:['Rana Daggubati','Anushka','Tamannaah'], synopsis:'The stunning conclusion reveals the truth behind Kattappa\'s betrayal as Baahubali reclaims his throne in the highest-grossing Indian film of its era \u2014 a global phenomenon.', dialogue:'తప్పు చేశావ్ దేవసేన... ఆడదాని వైపు చేయి వేస్తే నరకాల్సింది వేలు కాదు, తల!', trailer:'https://www.youtube.com/watch?v=G62HrubdD6o', release:'28 Apr 2017', budget:250, boxOffice:1810, runtime:171, music:'M. M. Keeravani', language:'Telugu, Tamil', ott:'Netflix' },
  { id:20, title:'Saaho', year:2019, poster:'https://upload.wikimedia.org/wikipedia/en/6/6b/Saaho_poster.jpg', genres:['Action','Thriller'], category:'action', badge:'Hit', badgeClass:'badge-hit', director:'Sujeeth', costars:['Shraddha Kapoor','Jackie Shroff'], synopsis:'A high-stakes heist thriller set across multiple countries, following a mysterious man whose hidden agenda puts him in the crosshairs of crime syndicates worldwide.', dialogue:'గల్లీలో సిక్స్ ఎవడైనా కొడతాడు... స్టేడియంలో కొట్టేవాడికే ఒక రేంజ్ ఉంటుంది!', trailer:'https://www.youtube.com/watch?v=lD0-ztCFydA', release:'30 Aug 2019', budget:350, boxOffice:433, runtime:170, music:'Tanishk Bagchi, Badshah', language:'Telugu, Hindi, Tamil', ott:'Netflix, Amazon Prime Video' },
  { id:21, title:'Radhe Shyam', year:2022, poster:'https://upload.wikimedia.org/wikipedia/en/5/5a/Radhe_Shyam.jpg', genres:['Romance','Drama'], category:'vintage', badge:'Romance', badgeClass:'badge-cult', director:'Radha Krishna Kumar', costars:['Pooja Hegde','Bhagyashree'], synopsis:'A charming palmist in 1970s Europe falls in love with a woman whose destiny he predicts will be tragic, leading to a battle against fate itself.', dialogue:'నీ ప్రేమ ఎదురు అవడం వరం. కానీ అందుకోవడం మాత్రం ఒక యుద్ధం.', trailer:'https://www.youtube.com/watch?v=ZAP6q_Zv-4g', release:'11 Mar 2022', budget:300, boxOffice:210, runtime:141, music:'Justin Prabhakaran', language:'Telugu, Hindi, Tamil', ott:'Amazon Prime Video' },
  { id:22, title:'Adipurush', year:2023, poster:'https://upload.wikimedia.org/wikipedia/en/c/cf/Adipurush_poster.jpeg', genres:['Action','Epic','Mythology'], category:'action', badge:'Epic', badgeClass:'badge-cult', director:'Om Raut', costars:['Kriti Sanon','Saif Ali Khan'], synopsis:'A grand retelling of the Ramayana, with Prabhas as Raghav (Lord Ram) in this visually ambitious mythological epic.', dialogue:'భూమి కృంగినా... నింగి చీలినా... న్యాయం చేతిలోనే అన్యాయానికి సర్వనాశనం!', trailer:'https://www.youtube.com/watch?v=X7lRGozX8KQ', release:'16 Jun 2023', budget:700, boxOffice:400, runtime:179, music:'Ajay-Atul', language:'Telugu, Hindi, Tamil', ott:'Netflix (Hindi), Amazon Prime Video (Telugu, Tamil, Kannada, Malayalam)' },
  { id:23, title:'Salaar: Part 1 \u2013 Ceasefire', year:2023, poster:'https://upload.wikimedia.org/wikipedia/en/a/a6/Salaar_Part_1_%E2%80%93_Ceasefire.jpg', genres:['Action','Dystopian'], category:'blockbuster', badge:'Blockbuster', badgeClass:'badge-blockbuster', director:'Prashanth Neel', costars:['Prithviraj','Shruti Haasan'], synopsis:'In a violent dystopian city-state, a fiercely loyal man rises to protect his friend and wage war against an oppressive regime in this adrenaline-fueled action epic.', dialogue:'వాడికి రూల్స్ తెలీవేమో... తెలిసినా వాడు ఫాలో అవ్వడేమో.', trailer:'https://www.youtube.com/watch?v=4GPvYMKtrtI', release:'22 Dec 2023', budget:400, boxOffice:700, runtime:175, music:'Ravi Basrur', language:'Telugu, Kannada, Hindi, Tamil', ott:'Netflix' },
  { id:24, title:'Kalki 2898 AD', year:2024, poster:'https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg', genres:['Sci-Fi','Action','Epic'], category:'action', badge:'Industry Hit', badgeClass:'badge-industry', director:'Nag Ashwin', costars:['Deepika Padukone','Amitabh Bachchan','Kamal Haasan'], synopsis:'Set in a dystopian future, a warrior from a forgotten age awakens to battle dark forces in this groundbreaking Indian sci-fi epic \u2014 the most expensive Indian film ever made.', dialogue:'రికార్డ్స్ చూస్కో... ఇప్పటి వరకు ఒక్క ఫైట్ కూడా ఓడిపోలేదు.', trailer:'https://www.youtube.com/watch?v=aninoDcPWo4', release:'27 Jun 2024', budget:600, boxOffice:1200, runtime:180, music:'Santhosh Narayanan', language:'Telugu, Hindi, Tamil, English', ott:'Netflix (Hindi), Amazon Prime Video (South languages)' },
  { id:25, title:'Kannappa', year:2025, poster:'https://upload.wikimedia.org/wikipedia/en/e/ed/Kannappa_(film).jpg', genres:['Action','Epic','Mythology'], category:'action', badge:'Cameo', badgeClass:'badge-cult', director:'Mukesh Kumar Singh', costars:['Vishnu Manchu','Mohan Babu'], synopsis:'Prabhas appears in a special cameo as Rudra in this epic mythological film based on the legend of Kannappa, the greatest devotee of Lord Shiva.', dialogue:'అన్ని ప్రయత్నాలు చేసావుగా... ఆఖరి ప్రయత్నంగా శివుడిని అడుగు. మనసారా అడిగితే కాదనడులే... భోళా శంకర్!', trailer:'https://www.youtube.com/results?search_query=Kannappa+2025+Prabhas+trailer', release:'25 Apr 2025', budget:100, boxOffice:80, runtime:155, music:'Stephen Devassy', language:'Telugu', ott:'Amazon Prime Video' },
  { id:26, title:'The RajaSaab', year:2026, poster:'https://upload.wikimedia.org/wikipedia/en/9/9e/The_RajaSaab_poster.jpg', genres:['Horror','Comedy','Romance'], category:'vintage', badge:'Hit', badgeClass:'badge-hit', director:'Maruthi Dasari', costars:['Nidhhi Agerwal','Riddhi Kumar'], synopsis:'A horror-comedy-romance where Prabhas plays Raju aka Raja Saab, who returns to his ancestral home and encounters supernatural forces with a humorous twist.', dialogue:'స్టార్ ఫైట్ స్టార్ట్స్... స్టార్ టు స్టార్... స్టార్ వార్స్!', trailer:'https://www.youtube.com/watch?v=wT4HcYAeV5U', release:'9 Jan 2026', budget:150, boxOffice:0, runtime:155, music:'Thaman S', language:'Telugu, Hindi', ott:'JioHotstar' },
  { id:27, title:'Fauzi', year:2026, poster:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0DKFjCSsAyTXiCZJi-_tZIZngYEq5mLz5Toi_XuHqfQ&s=10', genres:['Action','Period','War'], category:'action', badge:'Upcoming', badgeClass:'badge-blockbuster', director:'Hanu Raghavapudi', costars:['Imanvi','Mithun Chakraborty','Anupam Kher','Jaya Prada'], synopsis:'Set in 1940s colonial India, a fierce soldier fights alone against the British Raj in this epic period action drama — the bravest tale from the hidden chapters of Indian history.', dialogue:'ఒంటరిగా పోరాడే సైన్యం.', trailer:'https://www.youtube.com/results?search_query=Fauzi+2026+Prabhas+trailer', release:'3 Dec 2026', budget:200, boxOffice:0, runtime:0, music:'Vishal Chandrasekhar', language:'Telugu, Hindi, Tamil' },
  { id:28, title:'Spirit', year:2027, poster:'https://c.ndtvimg.com/2026-01/jveg6so4_ggg_625x300_01_January_26.jpeg', genres:['Action','Crime','Drama'], category:'action', badge:'Upcoming', badgeClass:'badge-blockbuster', director:'Sandeep Reddy Vanga', costars:['Triptii Dimri','Vivek Oberoi','Prakash Raj','Kanchana'], synopsis:'An angry young police officer behind bars takes on a mighty mafia syndicate in this raw, intense action drama from the director of Animal.', dialogue:'చిన్నప్పటి నుంచి నాకు ఒక చెడ్డ అలవాటు ఉంది.', trailer:'https://www.youtube.com/results?search_query=Spirit+2027+Prabhas+trailer', release:'05 Mar 2027', budget:300, boxOffice:0, runtime:0, music:'Harshavardhan Rameshwar', language:'Telugu, Hindi, Tamil' },
  { id:29, title:'Salaar: Part 2 \u2013 Shouryaanga Parvam', year:2026, poster:'https://upload.wikimedia.org/wikipedia/en/a/a6/Salaar_Part_1_%E2%80%93_Ceasefire.jpg', genres:['Action','Dystopian'], category:'action', badge:'Upcoming', badgeClass:'badge-blockbuster', director:'Prashanth Neel', costars:['Prithviraj','Shruti Haasan'], synopsis:'The brutal conclusion to the Salaar saga \u2014 Deva and Vardha\'s friendship faces its ultimate test as the Khansaar war reaches its explosive climax.', dialogue:'నేను శాంతిని కాదు — నేను యుద్ధాన్ని.', trailer:'https://www.youtube.com/results?search_query=Salaar+Part+2+trailer', release:'TBA', budget:400, boxOffice:0, runtime:0, music:'Ravi Basrur', language:'Telugu, Kannada, Hindi, Tamil' },
  { id:30, title:'Kalki 2', year:2027, poster:'https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg', genres:['Sci-Fi','Action','Epic'], category:'action', badge:'Upcoming', badgeClass:'badge-blockbuster', director:'Nag Ashwin', costars:['Deepika Padukone','Amitabh Bachchan','Kamal Haasan'], synopsis:'The prophesied saviour returns as the dark forces of Kali rise again. The sequel to India\'s most ambitious sci-fi epic continues the battle for humanity\'s future.', dialogue:'ప్రతి అంతం ఒక కొత్త ప్రారంభం.', trailer:'https://www.youtube.com/results?search_query=Kalki+2+trailer', release:'TBA', budget:700, boxOffice:0, runtime:0, music:'Santhosh Narayanan', language:'Telugu, Hindi, Tamil, English' },
  { id:31, title:'The RajaSaab 2', year:2027, poster:'https://upload.wikimedia.org/wikipedia/en/9/9e/The_RajaSaab_poster.jpg', genres:['Horror','Comedy','Romance'], category:'action', badge:'Upcoming', badgeClass:'badge-blockbuster', director:'Maruthi Dasari', costars:['Nidhhi Agerwal','Riddhi Kumar'], synopsis:'Raja Saab returns to his ancestral home where darker supernatural forces await. The horror-comedy-romance franchise expands with more thrills, laughs, and chills.', dialogue:'భయమూ సరదా కలిసొచ్చే కథ.', trailer:'https://www.youtube.com/results?search_query=The+RajaSaab+2+trailer', release:'TBA', budget:200, boxOffice:0, runtime:0, music:'Thaman S', language:'Telugu, Hindi' }
];

// ─── RENDER MOVIES ───
const grid = document.getElementById('movieGrid');
const filterTabs = document.getElementById('filterTabs');
const searchInput = document.getElementById('searchInput');

function renderMovies(filter='all', query='') {
  const filtered = movies.filter(m => {
    const matchFilter = filter === 'all' || m.category === filter;
    const matchQuery = !query || m.title.toLowerCase().includes(query.toLowerCase());
    return matchFilter && matchQuery;
  });
  if (!filtered.length) {
    grid.innerHTML = `<div style="grid-column:1/-1;text-align:center;padding:60px 0;color:rgba(255,255,255,0.3);">
      <i class="fas fa-film" style="font-size:2rem;margin-bottom:12px;display:block;"></i>
      No movies found. Try another search or filter.
    </div>`;
    return;
  }
  grid.innerHTML = filtered.map((m, i) => `
    <div class="movie-card fade-in" data-id="${m.id}" style="transition-delay:${i * 0.04}s;animation-delay:${i * 0.04}s">
      <div class="poster-wrap">
        <img src="${m.poster}" alt="${m.title}" loading="lazy" />
        <div class="poster-overlay">
          <div class="overlay-text">
            <span><i class="fas fa-star"></i> ${m.badge}</span>
            <span><i class="fas fa-info-circle"></i> Details</span>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="title-row">
          <h3>${m.title}</h3>
          <span class="year">${m.year}</span>
        </div>
        <div class="genres">${m.genres.map(g => `<span>${g}</span>`).join('')}</div>
        <span class="badge ${m.badgeClass}">${m.badge}</span>
        ${m.ott ? `<div class="ott-row"><i class="fas fa-play-circle"></i>${m.ott}</div>` : ''}
      </div>
    </div>
  `).join('');

  // Re-observe fade-ins for new cards
  grid.querySelectorAll('.movie-card').forEach(card => {
    observer.observe(card);
    card.addEventListener('click', () => openModal(Number(card.dataset.id)));
  });
}

// ─── FILTER / SEARCH ───
filterTabs.addEventListener('click', e => {
  const tab = e.target.closest('.filter-tab');
  if (!tab) return;
  filterTabs.querySelectorAll('.filter-tab').forEach(t => t.classList.remove('active'));
  tab.classList.add('active');
  renderMovies(tab.dataset.filter, searchInput.value);
});

searchInput.addEventListener('input', () => {
  const active = filterTabs.querySelector('.filter-tab.active');
  renderMovies(active.dataset.filter, searchInput.value);
});

// ─── BOX OFFICE DASHBOARD ───
function renderBoxOffice() {
  const body = document.getElementById('boxofficeBody');
  if (!body) return;
  const sorted = movies
    .filter(m => m.boxOffice > 0)
    .sort((a, b) => b.boxOffice - a.boxOffice);
  body.innerHTML = sorted.map((m, i) => `
    <div class="boxoffice-row">
      <div class="movie-name"><span class="rank-num">${i + 1}</span> ${m.title}</div>
      <div class="collection">₹${m.boxOffice.toLocaleString('en-IN')} Cr</div>
    </div>
  `).join('');
}
